# 1. 部署 PR 版本的 Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-pr-1
  namespace: bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: pr-1
  template:
    metadata:
      labels:
        app: ratings
        version: pr-1
    spec:
      containers:
      - name: ratings
        image: ghcr.io/villanel/staging-ratings:pr-1
        ports:
        - containerPort: 9080
        env:
        - name: PR_ID
          value: "1"
---
# 2. 为该服务嵌入染色路由
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ratings-pr-1-route
  namespace: bookinfo
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: ratings # 拦截发送给稳定版 Service 的流量
    port: 9080
  rules:
  - matches:
    - headers:
      - type: RegularExpression
        name: "baggage"
        value: ".*pr_id=1.*"
    backendRefs:
    - name: ratings-pr-1 # 转发给 PR 版 Deployment
      port: 9080